FROM python:3.6
ENV TZ=Asia/Shanghai
RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone

WORKDIR /usr/src/app

COPY ./rpc_server ./
RUN pip install -i https://mirrors.aliyun.com/pypi/simple/ --no-cache-dir -r reqiurements.txt

EXPOSE 12345
CMD [ "python", "./rpc_server.py" ]